version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: TravelCheck.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  worker:
    build:
      context: .
      dockerfile: TravelCheck.Worker/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development
